### ISSUE TITLE
Menu items disappear on click

### ISSUE THREAD

**Issue by andrew-codechimp** [andrew-codechimp/ha-menu#1]
Async update required.

**Comment by DominikPalo** [comment]
I have this issue also in the latest version (1.6): [![Screenshot from Gyazo](https://gyazo.com/3ff88a29f18f55a1f93f6412bbcbb36b/raw)](https://gyazo.com/3ff88a29f18f55a1f93f6412bbcbb36b)

macOS version: 10.15

**Comment by andrew-codechimp** [comment]
Working on this more, will get a new version out next week.
V 1.5 is actually a little bit more stable on that front at the moment.

**Comment by andrew-codechimp** [comment]
Fixed in V 1.7
