### ISSUE TITLE
OSX 10.15 required - Backport to 10.14?

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [andrew-codechimp/ha-menu#22]
My OSX says that I cannot run this application, since I have 10.14.6 (OSX Mojave).

Could you reduce the requirement to 10.14, so I don't have to upgrade for this app?

Thanks!

**Comment by andrew-codechimp** [comment]
Sorry I missed that.  Now targeting Mojave with 1.4 release 
https://github.com/andrew-codechimp/ha-menu/releases/tag/V1.4

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you very much!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Works fine on Mojave 👍

**Comment by andrew-codechimp** [comment]
Thanks for confirmation, I couldn't test it myself.
