### ISSUE TITLE
Limit which switches are shown

### ISSUE THREAD

**Issue by yayadrian** [andrew-codechimp/ha-menu#23]
Great app.
Please, could you limit which switches are  @shown? 
I've got quite a few in my system and I really don't need to see them all.

![image](https://user-images.githubusercontent.com/33496/69148099-6e191d80-0acb-11ea-8abb-4184ddab34c0.png)

**Comment by andrew-codechimp** [comment]
That's a lot of switches!  At the moment I query group.all_switches one easy solution is to allow you to specify a different group to display within preferences and you add all interesting switches to that group within HA.  That way this app doesn't need to keep a separate record of switches which could get out of date. 
Seeking opinion if that would be useable?

**Comment by yayadrian** [comment]
Using a specified group would be perfect. I do something similar for a Lovelace card.
It would also be useful to also hide switches with a state of "unavailable".

Loving this tiny little app

**Comment by andrew-codechimp** [comment]
Groups is mostly done, I'll look into the unavailable state. Makes sense to hide those. 
Hopefully releasing by end of week.

**Comment by andrew-codechimp** [comment]
Just released V1.5 which adds group support and better error handling.
https://github.com/andrew-codechimp/ha-menu/releases/tag/V1.5

**Comment by andrew-codechimp** [comment]
Seems to be an issue with certain HA versions, removed and re-opened issue

**Comment by andrew-codechimp** [comment]
Issue was unrelated to groups, new version 1.6 released
