### ISSUE TITLE
Cannot make a conection via http

### ISSUE THREAD

**Issue by crus1313** [andrew-codechimp/ha-menu#30]
I don't use "https" to connect to my hassio, so the application give me this message when I connect with via "http":
"App Transport security requires the use of secure connections"
If i put "https" it gives me :
"A SSL error has occurred and a secure connection to the server cannot be made"

Pleas allow "HTTP" as a connection.

ps.
my long token is good

**Comment by andrew-codechimp** [comment]
I use http to connect to an internal IP fine.  Are you trying to connect via an external facing IP/Domain that is HTTP?

**Comment by andrew-codechimp** [comment]
Found a fix for this and V1.10 should allow external http to be used.

**Comment by crus1313** [comment]
> I use http to connect to an internal IP fine. Are you trying to connect via an external facing IP/Domain that is HTTP?

Yes, over the internet. Did not tried locally :)
