### ISSUE TITLE
unsupported url

### ISSUE THREAD

**Issue by nickwild-999** [andrew-codechimp/ha-menu#35]
Hi Andrew,

Thanks for your work on this - should be really useful. However I am getting the above error.

All is good when I curl this through terminal. I am trying HAMenu 1.14.

Thanks

Nick

**Comment by andrew-codechimp** [comment]
The only time I'm seeing this is when you miss the http/https off the beginning of the URL.
Make sure you have something like this  http://yourIP or Domain:8123

**Comment by nickwild-999** [comment]
Sorry that works many thanks. I had tried that previously but for some reason it had not worked, but all good now and I have closed
