### ISSUE TITLE
all_* groups will be removed in 0.104

### ISSUE THREAD

**Issue by bramkragten** [andrew-codechimp/ha-menu#36]
Making the initial setup stop working and requires the user to setup groups first. https://github.com/home-assistant/home-assistant/pull/23789

Maybe better to filter the entities based on domain and make an option for that?

**Comment by bramkragten** [comment]
Adding an option to add entities in the preferences of the app instead of creating a group would be a big win too.

**Comment by andrew-codechimp** [comment]
I saw this change was coming. I like the idea of defaulting to filtering domains unless you add a group.
I want to avoid having to maintain entities within ha-menu and making sudo groups to allow division.

**Comment by andrew-codechimp** [comment]
Added domains in V2.0.2 to give back the all_ functionality.
Thanks @bramkragten for the suggestion.
