### ISSUE TITLE
group all_switches and all_lights not found in HASSIO 0.104

### ISSUE THREAD

**Issue by pilot1981** [andrew-codechimp/ha-menu#38]
Hi,
in HASSIO 0.104 group all_switches was removed:

https://www.home-assistant.io/blog/2020/01/15/release-104/#breaking-changes

so your app don't find my switches in HASSIO, what you suggest to do to fix it?

**Comment by andrew-codechimp** [comment]
This is a breaking change in 0.104, only solution for now is to add your switches/lights to custom groups and remove all_ groups from the list.  I've updated the readme for new users but knew it'd catch a few people out who upgrade.
Working on a fix, see #36

**Comment by andrew-codechimp** [comment]
Fixed in V2.0.2 by adding domain support.
