### ISSUE TITLE
add input_select

### ISSUE THREAD

**Issue by basnijholt** [andrew-codechimp/ha-menu#39]
An `input_select` seems like something that would work well with this interface.

Context, for my use case.

My iMac's speakers are connected over Toslink, which means I cannot control the volume on the Mac (which I can only do on the speakers). However, Home Assistant can do this for me!

So I have added 10 `input_boolean`s with volume 0 to 10. Then I have an automation that makes sure only one `input_boolean` is selected and also sets the right volume.

![image](https://user-images.githubusercontent.com/6897215/72689172-fc7f3f00-3b0e-11ea-9050-9832ee6be4ce.png)

To accomplish this I need to have all [this](https://github.com/basnijholt/home-assistant-config/commit/fc88446fd886bf446ce9cbee8d006c9a3d2338f6) code.

With an `input_select` this would be much nicer!

**Comment by andrew-codechimp** [comment]
Nice proposal, I've not used input_select's myself but think it would be doable.  
Probably best to implement this as a drill in menu item, the name of the input_select shown in the main menu, hovering on that shows the options.
I'll add it to my todo list.

**Comment by basnijholt** [comment]
Cool! I think this could have **many** usecases! 😄

**Comment by basnijholt** [comment]
FYI, I am showing off `ha-menu` [here](https://www.reddit.com/r/homeassistant/comments/eri64c/i_can_now_sync_the_speaker_volume_using_the_menu/) 😇

**Comment by andrew-codechimp** [comment]
I have my first fanboy :)  Much appreciated, I'm surprised how much attention this project has got for what started out as an experiment.
I have input_select's working, first time doing nested menu's but it seems to be OK.  A bit more testing required before I release it though.

**Comment by basnijholt** [comment]
That's great! I'll happily be a beta tester.

**Comment by rmarkle** [comment]
Same here!

**Comment by andrew-codechimp** [comment]
Input_selects are now supported with pre-release 2.1.0 please let me know how it goes and I'll hopefully release fully in a few days.
https://github.com/andrew-codechimp/ha-menu/releases/tag/2.1.0

**Comment by basnijholt** [comment]
Great, I will try it out 👍

**Comment by basnijholt** [comment]
It works great for me :tada:

[This ](https://github.com/basnijholt/home-assistant-config/commit/551be9025ababc483159910bdae0bcc23038e929) is how greatly I could simplify my code, could remove ~90 lines :)

**Comment by andrew-codechimp** [comment]
Thanks for the quick feedback. Your config is a lot simpler and I've had a browse of it this week for inspiration.
It's actually got me using input_select's myself now!
